# AI Commits Configuration File
# You can customize your settings here.
api:
  # Your OpenAI API key.
  # If left blank, the tool will try to use the OPENAI_API_KEY environment variable.
  key: 
  base_url: 
model:
  # The model to use for generating text.
  name: codedrive-chat
  # Temperature for commit message generation (0.0 to 1.0).
  # Higher values mean more creative, lower values mean more deterministic.
  commit_temperature: 0.7
  # Temperature for solution generation.
  solution_temperature: 0.5
  max_tokens_commit: 60
  max_tokens_solution: 512