version: '3.8'

services:
  nexcode_web:
    build:
      context: ..
      dockerfile: docker/nexcode_web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ../nexcode_web:/app
    depends_on:
      - nexcode_server

  nexcode_server:
    build:
      context: ..
      dockerfile: docker/nexcode_server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_BASE=https://api.openai.com/v1
      - OPENAI_MODEL=gpt-3.5-turbo
      - HOST=0.0.0.0
      - PORT=8000
      - REQUIRE_AUTH=false
      - API_TOKEN=your-server-token
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/nexcode
    volumes:
      - ../nexcode_server:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexcode
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 